### ISSUE TITLE
timeout error when using ssh adaptor

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/Xenon-examples#13]
(attempt to talk to live system)
URI passed via Program arguments in Eclipse:
```
ssh://jspaaks@lisa.surfsara.nl:22
```
(Properties of the object look normal).

```
// create the credential
Credential credential = credentials.newPasswordCredential("ssh", "jspaaks", 
"secretpasswd".toCharArray(), null);

Scheduler scheduler = jobs.newScheduler(location.getScheme(), 
location.getAuthority(), credential, null);
```
credential is created but scheduler fails (immediately, with timeout error):
```
ListJobsLisa example failed: ssh adaptor: timeout: socket is not established
nl.esciencecenter.xenon.InvalidLocationException: ssh adaptor: timeout: socket is not established
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.createSession(SshMultiplexedSession.java:241)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.createSession(SshMultiplexedSession.java:153)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.<init>(SshMultiplexedSession.java:130)
	at nl.esciencecenter.xenon.adaptors.ssh.SshAdaptor.createNewSession(SshAdaptor.java:281)
	at nl.esciencecenter.xenon.adaptors.ssh.SshJobs.newScheduler(SshJobs.java:114)
	at nl.esciencecenter.xenon.engine.jobs.JobsEngine.newScheduler(JobsEngine.java:49)
	at nl.esciencecenter.xenon.examples.jobs.ListJobsLisa.main(ListJobsLisa.java:72)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.createSession(SshMultiplexedSession.java:233)
	... 6 more

```

**Comment by jspaaks** [comment]
It seems to work after:
```
# change into home
cd ~
# rename ssh dir to a temporary name (for testing)
mv .ssh __.ssh__
# make an empty .ssh
mkdir .ssh
# make an empty known_hosts
touch known_hosts
```
so I guess the question is how do you set xenon to ignore whatever is in .ssh and use the supplied user/pwd combination. Maybe through XenonProperties. Would be nice to have the following default behavior:
- if user supplies pwd, use that, ignore stuff from .ssh
- if there's no password, fall back on using stuff from .ssh

**Comment by blootsvoets** [comment]
There are compounding factors here: SSH uses `known_hosts` to determine if the host you are connecting to is the same host as it was before. Otherwise, you are possibly connecting to a malicious host. The Lisa server might have changed since you first logged in, so SSH detects host spoofing. SURFsara on the matter: last paragraph of https://userinfo.surfsara.nl/systems/shared/ssh.

OpenSSH behaviour: unless explicitly told to ignore `known_hosts`, exit and print a message with the above description.
Xenon (JSch) behaviour: unless explicitly told to ignore `known_hosts`, throw an exception without any information.

It is already possible to ignore `known_hosts` in Xenon, that would cancel the exception. The lack of user feedback is a real problem, but this is hard to fix without removing JSch.

**Comment by jspaaks** [comment]
I made a [new issue](https://github.com/NLeSC/Xenon/issues/347) in the Xenon repository for the remainder of this issue.
