### ISSUE TITLE
run-examples.sh sometimes errors with message 'ssh adaptor: session is down'

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/Xenon-examples#5]
```
+ class_path='build/libs/*-all.jar'
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.CreatingXenon
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.CreatingXenonWithProperties
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.credentials.CreatingCredential
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.CreateLocalFileSystem
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.CreateFileSystem file:///
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.CreateFileSystem ssh://daisycutter@localhost
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.DirectoryListing file:///home/daisycutter/github/nlesc/xenon-examples
Directory file:///home/daisycutter/github/nlesc/xenon-examples exists and contains the following:
   .travis-ssh.sh
   run-examples.sh
   .gitignore
   doc
   build
   .git
   gradlew.bat
   gradlew
   .travis.yml
   gradle
   build.gradle
   LICENSE
   src
   .gradle
   README.md
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.DirectoryListing ssh://daisycutter@localhost/home/daisycutter/github/nlesc/xenon-examples
DirectoryListing example failed: ssh adaptor: session is down
nl.esciencecenter.xenon.XenonException: ssh adaptor: session is down
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:174)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.getSftpChannel(SshMultiplexedSession.java:290)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:120)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:160)
	at nl.esciencecenter.xenon.engine.files.FilesEngine.newFileSystem(FilesEngine.java:96)
	at nl.esciencecenter.xenon.examples.files.DirectoryListing.main(DirectoryListing.java:59)
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:762)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:171)
	... 5 more
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.LocalFileExists /home/daisycutter/github/nlesc/xenon-examples/README.md
File /home/daisycutter/github/nlesc/xenon-examples/README.md exists!
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.FileExists file:///home/daisycutter/github/nlesc/xenon-examples/README.md
File file:///home/daisycutter/github/nlesc/xenon-examples/README.md exists!
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.FileExists ssh://daisycutter@localhost//home/daisycutter/github/nlesc/xenon-examples/README.md
FileExists example failed: ssh adaptor: session is down
nl.esciencecenter.xenon.XenonException: ssh adaptor: session is down
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:174)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.getSftpChannel(SshMultiplexedSession.java:290)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:120)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:160)
	at nl.esciencecenter.xenon.engine.files.FilesEngine.newFileSystem(FilesEngine.java:96)
	at nl.esciencecenter.xenon.examples.files.FileExists.main(FileExists.java:61)
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:762)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:171)
	... 5 more
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.ShowFileAttributes file:///home/daisycutter/github/nlesc/xenon-examples/README.md
File file:///home/daisycutter/github/nlesc/xenon-examples/README.md exists and has the following attributes:
  isDirectory: false
  isSymbolicLink: false
  size: 2377
  owner: daisycutter
  group: daisycutter
  permissions: [OWNER_READ, OTHERS_READ, GROUP_READ, OWNER_WRITE, GROUP_WRITE]
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.ShowFileAttributes ssh://daisycutter@localhost//home/daisycutter/github/nlesc/xenon-examples/README.md
ShowFileAttributes example failed: ssh adaptor: session is down
nl.esciencecenter.xenon.XenonException: ssh adaptor: session is down
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:174)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.getSftpChannel(SshMultiplexedSession.java:290)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:120)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:160)
	at nl.esciencecenter.xenon.engine.files.FilesEngine.newFileSystem(FilesEngine.java:96)
	at nl.esciencecenter.xenon.examples.files.ShowFileAttributes.main(ShowFileAttributes.java:59)
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:762)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:171)
	... 5 more
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.CopyFile file:///home/daisycutter/github/nlesc/xenon-examples/README.md file:///tmp/Copy.Of.README.md
+ ls /tmp/Copy.Of.README.md
/tmp/Copy.Of.README.md
+ rm /tmp/Copy.Of.README.md
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitSimpleBatchJob local:///
Job ran succesfully!
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitSimpleBatchJob ssh://daisycutter@localhost
Job ran succesfully!
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitBatchJobWithOutput local:///
Job ran succesfully and produced:
 STDOUT: daisycutter-NLeSC

 STDERR: 
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitBatchJobWithOutput ssh://daisycutter@localhost
SubmitBatchJob example failed: ssh adaptor: session is down
nl.esciencecenter.xenon.XenonException: ssh adaptor: session is down
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:174)
	at nl.esciencecenter.xenon.adaptors.ssh.SshMultiplexedSession.getSftpChannel(SshMultiplexedSession.java:290)
	at nl.esciencecenter.xenon.adaptors.ssh.SshFiles.newFileSystem(SshFiles.java:120)
	at nl.esciencecenter.xenon.adaptors.ssh.SshJobs.newScheduler(SshJobs.java:123)
	at nl.esciencecenter.xenon.engine.jobs.JobsEngine.newScheduler(JobsEngine.java:49)
	at nl.esciencecenter.xenon.examples.jobs.SubmitBatchJobWithOutput.main(SubmitBatchJobWithOutput.java:67)
Caused by: com.jcraft.jsch.JSchException: session is down
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:762)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at nl.esciencecenter.xenon.adaptors.ssh.SshSession.getSftpChannel(SshSession.java:171)
	... 5 more
+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitInteractiveJobWithOutput ssh://daisycutter@localhost
Job ran succesfully and produced: daisycutter-NLeSC

+ java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.ListJobs local:///
The scheduler at local:/// has 1 jobs:
  local-0

```

**Comment by sverhoeven** [comment]
Please clarify `sometimes`. Do the following openssl commands work?
```
ssh $USER@localhost hostname
scp $USER@lcoalhost:$PWD/README.md /tmp/Copy.Of.README.md
```

**Comment by jspaaks** [comment]
```
daisycutter@daisycutter-NLeSC:~/github/nlesc/xenon-examples$ ssh $USER@localhost hostname
daisycutter-NLeSC
daisycutter@daisycutter-NLeSC:~/github/nlesc/xenon-examples$ ls -l README.md 
-rw-rw-r-- 1 daisycutter daisycutter 2377 2015-12-04 14:45 README.md
daisycutter@daisycutter-NLeSC:~/github/nlesc/xenon-examples$ scp $USER@lcoalhost:$PWD/README.md /tmp/Copy.Of.README.md
ssh: Could not resolve hostname lcoalhost: Name or service not known
daisycutter@daisycutter-NLeSC:~/github/nlesc/xenon-examples$ scp $USER@localhost:$PWD/README.md /tmp/Copy.Of.README.md
README.md                                                                                                       100% 2377     2.3KB/s   00:00    
```

**Comment by jspaaks** [comment]
so I still have this intermittent problem
I started 
```bash
java -Dloglevel=ERROR -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.files.CreateFileSystem ssh://daisycutter@localhost
```
X times, here are the results:
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass
1. pass

**Comment by jspaaks** [comment]
Looks like this issue has gone away since the updates relating to .ssh/known_hosts and .ssh/config (e.g. [here](https://github.com/NLeSC/Xenon/issues/354))
